### ISSUE TITLE
Compilation errors on Win/MinGW and Mac OS X

### ISSUE THREAD

**Issue by seladb** [rvelea/LightPcapNg#1]
Hi, I would like to know which OS's are supported? I'm trying to compile LightPcapNg on Windows using MinGW32 & MinGW-w64 and on Mac OS X and I get the following compilation errors:

Mac OS X:
`LightPcapNg/src/light_alloc.c:50:2: error: unknown type name 'ssize_t'; did you mean 'size_t'?`

Win/MinGW32:
`LightPcapNg/src/light_alloc.c:50:2: error: unknown type name 'ssize_t'`

Win/MinGW-w64:
`LightPcapNg/src/light_manipulate.c:33:23: fatal error: arpa/inet.h: No such file or directory`

**Comment by rvelea** [comment]
Hello,

For now I only support Linux. All the tests and work I've done have been done on Ubuntu.

It shouldn't be hard to port existing work on Windows but it's not something I'm working at the moment.

Thanks,

Radu

**Comment by seladb** [comment]
I already fixed this issue in the pull request #2 that you just merged
